services:
  - type: web
    name: PETER-PARKER-BOT
    plan: free
    runtime: python
    repo: https://github.com/matrixbotz0/PETER-PARKER-BOT.git
    branch: main

    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py

    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: AUTH_CHANNEL
        sync: false
      - key: DATABASE_NAME
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: PICS
        sync: false
      - key: ADMINS
        sync: false
      - key: LOG_CHANNEL
        sync: false

    env:
      pythonVersion: 3.10.8

    autoDeploy: false
